<?xml version="1.0"?>
<robot name="suitcase"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <property name="suitcase_height" value="0.191" />
  <property name="suitcase_width" value="0.288" />
  <property name="suitcase_depth" value="0.514" />
  <property name="suitcase_x" value="0.0" />
  <property name="suitcase_y" value="0.0" />
  <property name="suitcase_z" value="0.0" />

  <property name="suitcase_wall_thickness" value="0.01"/>

  <property name="M_PI" value="3.1415926535897931" />

  <property name="lock_height" value="0.02" />
  <property name="lock_width" value="0.1" />
  <property name="lock_depth" value="0.1" />


  <link name="suitcase_bottom_link">
    <inertial>
      <mass value="20.0" />
      <origin xyz="${suitcase_x} ${suitcase_y} ${suitcase_z+suitcase_wall_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
    <visual>
      <origin xyz="${suitcase_x} ${suitcase_y} ${suitcase_z+suitcase_wall_thickness/2}" />
      <geometry>
        <box size="${suitcase_width} ${suitcase_depth} ${suitcase_wall_thickness}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${suitcase_x} ${suitcase_y} ${suitcase_z+suitcase_wall_thickness/2}" />
      <geometry>
        <box size="${suitcase_width} ${suitcase_depth} ${suitcase_wall_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="suitcase_bottom_link">
    <material>Gazebo/Red</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <joint name="wall1_joint" type="fixed" >
    <parent link="suitcase_bottom_link" />
    <origin xyz="${suitcase_x+suitcase_width/2} ${suitcase_y} ${suitcase_z}" rpy="0 0 0" />
    <child link="wall1_link" />
  </joint>
  <link name="wall1_link">
    <inertial>
      <mass value="3.0" />
      <origin xyz="0 0 ${suitcase_height/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${suitcase_wall_thickness} ${suitcase_depth} ${suitcase_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${suitcase_wall_thickness} ${suitcase_depth} ${suitcase_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="wall1_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="wall2_joint" type="fixed" >
    <parent link="suitcase_bottom_link" />
    <origin xyz="${suitcase_x-suitcase_width/2} ${suitcase_y} ${suitcase_z}" rpy="0 0 0" />
    <child link="wall2_link" />
  </joint>
  <link name="wall2_link">
    <inertial>
      <mass value="3.0" />
      <origin xyz="0 0 ${suitcase_height/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${suitcase_wall_thickness} ${suitcase_depth} ${suitcase_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${suitcase_wall_thickness} ${suitcase_depth} ${suitcase_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="wall2_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="wall3_joint" type="fixed" >
    <parent link="suitcase_bottom_link" />
    <origin xyz="${suitcase_x} ${suitcase_y+suitcase_depth/2} ${suitcase_z}" rpy="0 0 0" />
    <child link="wall3_link" />
  </joint>
  <link name="wall3_link">
    <inertial>
      <mass value="3.0" />
      <origin xyz="0 0 ${suitcase_height/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${suitcase_width} ${suitcase_wall_thickness} ${suitcase_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${suitcase_width} ${suitcase_wall_thickness} ${suitcase_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="wall3_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="wall4_joint" type="fixed" >
    <parent link="suitcase_bottom_link" />
    <origin xyz="${suitcase_x} ${suitcase_y-suitcase_depth/2} ${suitcase_z}" rpy="0 0 0" />
    <child link="wall4_link" />
  </joint>
  <link name="wall4_link">
    <inertial>
      <mass value="3.0" />
      <origin xyz="0 0 ${suitcase_height/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${suitcase_width} ${suitcase_wall_thickness} ${suitcase_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${suitcase_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${suitcase_width} ${suitcase_wall_thickness} ${suitcase_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="wall4_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>


  <joint name="lid_joint" type="revolute" >
    <axis xyz="0 -1 0"/>
    <limit effort="1000.0" lower="0.2" upper="${M_PI}" velocity="0.5"/>
    <parent link="wall1_link" />
    <!--origin xyz="${suitcase_x+suitcase_width/2} ${suitcase_y} ${suitcase_z+suitcase_height}" rpy="0 0 0" /-->
    <origin xyz="0 0 ${suitcase_height}" rpy="0 0 0" />
    <child link="suitcase_lid_link" />
    <dynamics damping="50.5"/>
  </joint>

  <link name="suitcase_lid_link">
    <inertial>
      <mass value="0.5" />
      <origin xyz="${suitcase_width/2} 0 0" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
    <visual>
      <origin xyz="${suitcase_width/2} 0 0" />
      <geometry>
        <box size="${suitcase_width + 0.01} ${suitcase_depth + 0.01} ${suitcase_wall_thickness}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${suitcase_width/2} 0 0" />
      <geometry>
        <box size="${suitcase_width + 0.01} ${suitcase_depth + 0.01} ${suitcase_wall_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="suitcase_lid_link">
    <material>Gazebo/Red</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <joint name="lock1_joint" type="fixed" >
    <parent link="suitcase_lid_link" />
    <origin xyz="${suitcase_width} -0.15 0" rpy="0 0 0" />
    <child link="lock1_link" />
  </joint>
  <link name="lock1_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="${lock_width/2} 0 ${lock_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="${lock_width/2} 0 ${lock_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${lock_width} ${lock_depth} ${lock_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${lock_width/2} 0 ${lock_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${lock_width} ${lock_depth} ${lock_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="lock1_link">
    <material>Gazebo/Grey</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="lock2_joint" type="fixed" >
    <parent link="suitcase_lid_link" />
    <origin xyz="${suitcase_width} 0.15 0" rpy="0 0 0" />
    <child link="lock2_link" />
  </joint>
  <link name="lock2_link">
    <inertial>
      <mass value="0.1" />
      <origin xyz="${lock_width/2} 0 ${lock_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="${lock_width/2} 0 ${lock_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${lock_width} ${lock_depth} ${lock_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${lock_width/2} 0 ${lock_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${lock_width} ${lock_depth} ${lock_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="lock2_link">
    <material>Gazebo/Grey</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <gazebo>
    <!--static>true</static-->
    <turnGravityOff>false</turnGravityOff>
    <canonicalBody>suitcase_bottom_link</canonicalBody>
  </gazebo>


</robot>
